### ISSUE TITLE
Twispay_Subscription_Processor::process and Twispay_Subscription_Processor::prepare_request_data is never called

### ISSUE THREAD

**Issue by lakshmana** [Twispay/WooCommerce#19]
In previous version 1.0.12, if multiple subscriptions were added in the cart, twispay plugin would show error as follows: "Orders with subscriptions cannot have other products too” from` Twispay::twispay_subscription_processor`

In the latest version, the processor for subscription is now moved to new class ie `Twispay_Subscription_Processor`.  Looking at this class code, this class also has a section where it checks for multiple subscriptions in a single order on line no 108  [](https://github.com/Twispay/WooCommerce/blob/b17d626bd07bac816149086c748d20689f634e79/Twispay%20WooCommerce%20Plugin/twispay/includes/processors/class-subscription-processor.php#L108) However in my tests, this `Twispay_Subscription_Processor:process` is never called because there is nothing in $_GET and I can place order with multiple subscription. 

Also, with previous version that only supported single subscription per order, the order detail in twispay dashboard would should as follows. Here you can see that the order type is recurring and it shows Re-billing Date and Re-bill Interval for subscription.
![image](https://user-images.githubusercontent.com/3132026/142866607-aa122b2a-b693-4b33-8bb6-665b478fc894.png)

However with the order (with multiple subscriptions) placed with latest plugin, the Re-billing Date and the Re-bill Interval shows invalid and null respectively. 
![image](https://user-images.githubusercontent.com/3132026/142867039-a8435ce1-4ea7-4cd0-a8d2-f063bd87cec2.png)

For us, this is great as we can now place order with multiple subscriptions in single order, which was not possible in previous version. Anyway, can you please confirm if this is normal  and we can now place multiple subscriptions in single order in the latest plugin and it is stable to use in production ?

**Comment by lakshmana** [comment]
The latest version also seems to not support woocommerce subscription at all by looking at the twispay dashaboard. As you can see in the screenshot below, the order placed with the latest version of the plugin does not have re-bill interval.
![image](https://user-images.githubusercontent.com/3132026/142884045-3c2ee96d-43ab-4ce3-9239-7ce7b147d9d3.png)

order placed with the latest plugin
![image](https://user-images.githubusercontent.com/3132026/142884238-13962c0a-20c0-4d74-bc3d-70d07fe9ce1e.png)

order placed with the old version (1.0.12)
![image](https://user-images.githubusercontent.com/3132026/142884326-d2b0660e-49e8-46b7-a108-a7c61a0c6fb3.png)

Can anyone do some tests with subscriptions ? 
Thx
Laxman

**Comment by carco** [comment]
Hi @lakshmana,
The problem(s) seem to be triggered by (order_id is integer):
```if ($this->order_id !== null && strpos($this->order_id, '_sub') !== false)```
in both processor files (class-subscription-processor.php and class-main-processor.php).

A (quick) solution (until we will fix & release a new version) is to replace (in BOTH files) :
```strpos($this->order_id, '_sub') ```
with
```strpos($_GET['order_id'], '_sub')```

About " we can now place order with multiple subscriptions in single order", unfortunately is NOT possible (the API doesn't support this).


Sorry for delay.

**Comment by carco** [comment]
Fixed on #21
